/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gabriel.frame;

import br.com.gabriel.objeto.Aluno;
import br.com.gabriel.objeto.Nota;
import br.com.gabriel.objeto.TipoAvaliacao;
import javax.swing.JOptionPane;

/**
 *
 * @author SATC
 */
public class Principal extends javax.swing.JFrame {

    Aluno a;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo = new javax.swing.JLabel();
        jPAluno = new javax.swing.JPanel();
        jLTituloAluno = new javax.swing.JLabel();
        jLMatriculaAluno = new javax.swing.JLabel();
        jTFMatriculaAluno = new javax.swing.JTextField();
        jLNomeAluno = new javax.swing.JLabel();
        jTFNomeAluno = new javax.swing.JTextField();
        jBCadastrarAluno = new javax.swing.JButton();
        jPNomedaDisciplina = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLTituloNomedaDisciplina = new javax.swing.JLabel();
        jTFNomedaDisciplina = new javax.swing.JTextField();
        jCBNomedaDisciplina = new javax.swing.JComboBox<>();
        jLTituloNotas = new javax.swing.JLabel();
        jLN1Notas = new javax.swing.JLabel();
        jLN2Notas = new javax.swing.JLabel();
        jLN3Notas = new javax.swing.JLabel();
        jLN4Notas = new javax.swing.JLabel();
        jTFN1Notas = new javax.swing.JTextField();
        jTFN2Notas = new javax.swing.JTextField();
        jTFN3Notas = new javax.swing.JTextField();
        jTFN4Notas = new javax.swing.JTextField();
        jBCalcularNotas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLTitulo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLTitulo.setText("Consulta de Disciplina");

        jPAluno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLTituloAluno.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLTituloAluno.setText("Aluno");

        jLMatriculaAluno.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLMatriculaAluno.setText("Matrícula");

        jTFMatriculaAluno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLNomeAluno.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLNomeAluno.setText("Nome");

        jTFNomeAluno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jBCadastrarAluno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBCadastrarAluno.setText("Cadastrar");
        jBCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPAlunoLayout = new javax.swing.GroupLayout(jPAluno);
        jPAluno.setLayout(jPAlunoLayout);
        jPAlunoLayout.setHorizontalGroup(
            jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPAlunoLayout.createSequentialGroup()
                .addGroup(jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPAlunoLayout.createSequentialGroup()
                        .addGroup(jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPAlunoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLMatriculaAluno)
                                    .addComponent(jLNomeAluno)))
                            .addGroup(jPAlunoLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLTituloAluno)))
                        .addGap(0, 56, Short.MAX_VALUE))
                    .addGroup(jPAlunoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFNomeAluno)
                            .addComponent(jTFMatriculaAluno))))
                .addContainerGap())
            .addGroup(jPAlunoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jBCadastrarAluno)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPAlunoLayout.setVerticalGroup(
            jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTituloAluno)
                .addGap(18, 18, 18)
                .addComponent(jLMatriculaAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFMatriculaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLNomeAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jBCadastrarAluno)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPNomedaDisciplina.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLTituloNomedaDisciplina.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLTituloNomedaDisciplina.setText("Nome da Disciplina");

        jTFNomedaDisciplina.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jCBNomedaDisciplina.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCBNomedaDisciplina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PROVA", "TRABALHO", "SEMINARIO" }));
        jCBNomedaDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBNomedaDisciplinaActionPerformed(evt);
            }
        });

        jLTituloNotas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLTituloNotas.setText("Notas");

        jLN1Notas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLN1Notas.setText("N1");

        jLN2Notas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLN2Notas.setText("N2");

        jLN3Notas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLN3Notas.setText("N3");

        jLN4Notas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLN4Notas.setText("N4");

        jTFN1Notas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTFN2Notas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTFN3Notas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTFN4Notas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jBCalcularNotas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBCalcularNotas.setText("Calcular");
        jBCalcularNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalcularNotasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPNomedaDisciplinaLayout = new javax.swing.GroupLayout(jPNomedaDisciplina);
        jPNomedaDisciplina.setLayout(jPNomedaDisciplinaLayout);
        jPNomedaDisciplinaLayout.setHorizontalGroup(
            jPNomedaDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPNomedaDisciplinaLayout.createSequentialGroup()
                .addGroup(jPNomedaDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPNomedaDisciplinaLayout.createSequentialGroup()
                        .addGroup(jPNomedaDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPNomedaDisciplinaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTFNomedaDisciplina))
                            .addGroup(jPNomedaDisciplinaLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLTituloNomedaDisciplina)
                                .addGap(0, 1, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(jPNomedaDisciplinaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jCBNomedaDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPNomedaDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPNomedaDisciplinaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPNomedaDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLN3Notas)
                            .addComponent(jLN4Notas)
                            .addGroup(jPNomedaDisciplinaLayout.createSequentialGroup()
                                .addGroup(jPNomedaDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLN1Notas)
                                    .addComponent(jLN2Notas))
                                .addGap(25, 25, 25)
                                .addGroup(jPNomedaDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLTituloNotas)
                                    .addGroup(jPNomedaDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTFN1Notas, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                        .addComponent(jTFN2Notas)
                                        .addComponent(jTFN3Notas)
                                        .addComponent(jTFN4Notas))))))
                    .addGroup(jPNomedaDisciplinaLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jBCalcularNotas)))
                .addGap(25, 25, 25))
        );
        jPNomedaDisciplinaLayout.setVerticalGroup(
            jPNomedaDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPNomedaDisciplinaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPNomedaDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPNomedaDisciplinaLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLTituloNomedaDisciplina)
                        .addGap(18, 18, 18)
                        .addComponent(jTFNomedaDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCBNomedaDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPNomedaDisciplinaLayout.createSequentialGroup()
                        .addComponent(jLTituloNotas)
                        .addGap(18, 18, 18)
                        .addGroup(jPNomedaDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFN1Notas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLN1Notas))
                        .addGap(18, 18, 18)
                        .addGroup(jPNomedaDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLN2Notas)
                            .addComponent(jTFN2Notas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPNomedaDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLN3Notas)
                            .addComponent(jTFN3Notas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPNomedaDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLN4Notas)
                    .addComponent(jTFN4Notas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCalcularNotas)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPNomedaDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLTitulo)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPNomedaDisciplina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarAlunoActionPerformed
        // TODO add your handling code here:
        String nome = jTFNomeAluno.getText();
        int matricula = 0;
        try{
        matricula = Integer.parseInt(jTFMatriculaAluno.getText());
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Você digitou um caractere inválido! ");
            throw new RuntimeException();
        }
        a = new Aluno(nome, matricula);
        JOptionPane.showMessageDialog(null, a.toString());
    }//GEN-LAST:event_jBCadastrarAlunoActionPerformed

    private void jCBNomedaDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBNomedaDisciplinaActionPerformed
        // TODO add your handling code here:       
    }//GEN-LAST:event_jCBNomedaDisciplinaActionPerformed

    private void jBCalcularNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalcularNotasActionPerformed
        // TODO add your handling code here:
        Aluno a = new Aluno(jTFNomeAluno.getText(), Integer.parseInt(jTFMatriculaAluno.getText()));
        String nomeDisciplina;
        float n1, n2, n3, n4, media;

        nomeDisciplina = this.jTFNomedaDisciplina.getText();
        n1 = Float.parseFloat(this.jTFN1Notas.getText());
        n2 = Float.parseFloat(this.jTFN2Notas.getText());
        n3 = Float.parseFloat(this.jTFN3Notas.getText());
        n4 = Float.parseFloat(this.jTFN4Notas.getText());
        media = (n1 + n2 + n3 + n4) / 4;

        TipoAvaliacao tipo = null;
        switch (jCBNomedaDisciplina.getSelectedIndex()) {

            case 0: {
                tipo = TipoAvaliacao.PROVA;
                JOptionPane.showMessageDialog(this, a.toString() + "\n" + "Disciplina: " + nomeDisciplina + "\n" + tipo.getTipoAvaliacao());
                break;
            }
            case 1: {
                tipo = TipoAvaliacao.TRABALHO;
                break;
            }
            case 2: {
                tipo = TipoAvaliacao.SEMINARIO;
                break;
            }
        }
        a.getNotas().add(new Nota(jTFNomedaDisciplina.getText(), tipo, Float.parseFloat(jTFN1Notas.getText())));
        a.getNotas().add(new Nota(jTFNomedaDisciplina.getText(), tipo, Float.parseFloat(jTFN2Notas.getText())));
        a.getNotas().add(new Nota(jTFNomedaDisciplina.getText(), tipo, Float.parseFloat(jTFN3Notas.getText())));
        a.getNotas().add(new Nota(jTFNomedaDisciplina.getText(), tipo, Float.parseFloat(jTFN4Notas.getText())));
    }//GEN-LAST:event_jBCalcularNotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrarAluno;
    private javax.swing.JButton jBCalcularNotas;
    private javax.swing.JComboBox<String> jCBNomedaDisciplina;
    private javax.swing.JLabel jLMatriculaAluno;
    private javax.swing.JLabel jLN1Notas;
    private javax.swing.JLabel jLN2Notas;
    private javax.swing.JLabel jLN3Notas;
    private javax.swing.JLabel jLN4Notas;
    private javax.swing.JLabel jLNomeAluno;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLTituloAluno;
    private javax.swing.JLabel jLTituloNomedaDisciplina;
    private javax.swing.JLabel jLTituloNotas;
    private javax.swing.JPanel jPAluno;
    private javax.swing.JPanel jPNomedaDisciplina;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFMatriculaAluno;
    private javax.swing.JTextField jTFN1Notas;
    private javax.swing.JTextField jTFN2Notas;
    private javax.swing.JTextField jTFN3Notas;
    private javax.swing.JTextField jTFN4Notas;
    private javax.swing.JTextField jTFNomeAluno;
    private javax.swing.JTextField jTFNomedaDisciplina;
    // End of variables declaration//GEN-END:variables
}
